/** \file
    Download the résumés listes in a CSV file generated by Talemetry

    \author Ronan Keryell
*/
#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
// Waiting for C++20 library
//#include <span>
#include <string>
#include <boost/process.hpp>
#include <range/v3/all.hpp>
// TODO add to range-v3/include/range/v3/view.hpp
#include <range/v3/view/remove.hpp>
namespace bp = boost::process;
using namespace ranges;

int main(int argc, char *argv[]) {
  // Go into a safer C++20 world
  // std::span args { argv + 1, argc - 1};
  // Skip the first argument which is actuall the program name
  for (auto i = 1; i < argc; ++i) {
    // Open each file from the names passe as argument
    auto file = std::ifstream { argv[i] };
    // Create a local subdirectory and works into it
    auto constexpr subdirectory = "CV";
    std::filesystem::create_directory(subdirectory);
    std::filesystem::current_path(subdirectory);
    // Iterate on all the lines but the first header one
    for (const auto & line : getlines_view { file } | views::tail) {
      std::cout << "Handling " << line << std::endl;
      auto columns = line
        // Remove There are still some raw '\r` because getlines_view cannot
        // handle yet MS-DOS text files in a unix environment
        | views::remove('\r')
        // Assume CSV fields separated by ',`.
        | views::split(',')
        // Put the result to a vector so we can easily access the last elememt
        | to<std::vector>;
      // Convert the last range of characters into a string
      auto url = to<std::string>(*columns.crbegin());
      // Rewrite the candidate URL to the candidate résumé URL
      auto resume_url = url + "/resume/download";
      resume_url = std::regex_replace(resume_url, std::regex { "/profiles/" },
                                      "/candidate/");
      // Use curl to do the real fetching, to handle HTTP protocol
      bp::system(bp::search_path("curl"),
                 // Use the name advertized by the server to store the file
                 "--remote-name", "--remote-header-name",
                 // Talemetry impose some browsers... :-(
                 // Just lie by imitating some other one
                 "--user-agent",
                 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0",
                 resume_url);
    }
  }
}
